[tool.poetry]
name = "chiru"
version = "0.7.0"
description = "Discord client library for AnyIO"
authors = ["Lura Skye <l@veriny.tf>"]
readme = "README.rst"
packages = [{include = "chiru", from = "src"}]
license = "LGPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.11"
httpx = "^0.25.0"
attrs = "^23.1.0"
stickney = {git = "https://github.com/Fuyukai/stickney.git"}
anyio = "^4.0.0"
cattrs = {git = "https://github.com/python-attrs/cattrs.git"}
arrow = "^1.3.0"
bitarray = "^2.8.2"

[tool.black]
line-length = 100
target-version = ["py311"]

[tool.isort]
profile = "black"
src_paths = ["src"]


[tool.poetry.group.dev.dependencies]
trio = "^0.23.0"
black = "^23.10.1"
isort = "^5.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
